services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - $PORT:$PORT
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "start:dev"]
